trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: ../job-param.yml
  parameters:
    addon: 'zigbee2mqtt-edge'
    extra_param: '--no-cache --docker-hub zigbee2mqtt'
