trigger:
  batch: true
  branches:
    include:
    - dev
  paths:
    include:
    - zigbee2mqtt-edge/config.json
    - zigbee2mqtt-edge/Dockerfile
    - zigbee2mqtt-edge/run.sh
    - zigbee2mqtt-edge/socat.sh

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: ../job-param.yml
  parameters:
    addon: 'zigbee2mqtt-edge'
    extra_param: '--no-cache'
