trigger:
  branches:
    include:
    - dev

pr:
  - dev

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: ../job-param.yml
  parameters:
    addon: 'zigbee2mqtt-edge'
    extra_param: '--no-latest --test'
