trigger:
  branches:
    include:
    - master
pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: ../job-param.yml
  parameters:
    addon: 'zigbee2mqtt'
    extra_param: '--no-latest --test'
