trigger:
  branches:
    include:
    - dev

pr:
  - dev

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: common-job-template.yml
  parameters:
    addon: 'zigbee2mqtt-edge'
    docker_env_param: '--env BUILD_EDGE=1'
    extra_param: '--no-latest --test'
